# Generated by Django 3.0.3 on 2020-05-21 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_alunousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrodebancadeproposta',
            name='proposta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='membros_da_banca', to='backend.Proposta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposta',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='aprovada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
