# Generated by Django 3.0.3 on 2020-06-04 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_funcionariousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='membrodebancadeproposta',
            name='membro_externo_cpf',
        ),
        migrations.RemoveField(
            model_name='membrodebancadeproposta',
            name='membro_externo_email',
        ),
        migrations.RemoveField(
            model_name='membrodebancadeproposta',
            name='membro_externo_instituicao',
        ),
        migrations.RemoveField(
            model_name='membrodebancadeproposta',
            name='membro_externo_nome',
        ),
        migrations.AlterField(
            model_name='membrodebancadeproposta',
            name='membro_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_em_bancas', to='backend.Funcionario'),
        ),
        migrations.CreateModel(
            name='ColaboradorExternoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_externo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='backend.ColaboradorExterno')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membro_externo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membrodebancadeproposta',
            name='membro_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_em_bancas', to='backend.ColaboradorExterno'),
        ),
    ]
